/**
 * coverageData.js
 * Full Bangladesh delivery coverage.
 * Each entry has: region, district, city, covered_area[], coords {lat, lng}
 * coords = district HQ centroid — used for map fallback if Nominatim fails.
 */

const coverageData = [
  /* ─── DHAKA ─── */
  {
    region: "Dhaka",
    district: "Dhaka",
    city: "Dhaka",
    covered_area: [
      "Uttara",
      "Dhanmondi",
      "Mirpur",
      "Mohammadpur",
      "Gulshan",
      "Banani",
      "Rayer Bazar",
      "Azimpur",
      "Lalbagh",
      "Motijheel",
      "Tejgaon",
      "Khilgaon",
      "Demra",
      "Jatrabari",
      "Bashabo",
      "Shyampur",
      "Badda",
      "Rampura",
    ],
    coords: { lat: 23.8103, lng: 90.4125 },
  },
  {
    region: "Dhaka",
    district: "Faridpur",
    city: "Faridpur",
    covered_area: [
      "Goalanda",
      "Boalmari",
      "Bhanga",
      "Sadarpur",
      "Nagarkanda",
      "Alfadanga",
      "Char Bhadrasan",
      "Madhukhali",
      "Saltha",
    ],
    coords: { lat: 23.607, lng: 89.839 },
  },
  {
    region: "Dhaka",
    district: "Gazipur",
    city: "Gazipur",
    covered_area: [
      "Tongi",
      "Kaliakair",
      "Sreepur",
      "Kapasia",
      "Kaliganj",
      "Joydebpur",
    ],
    coords: { lat: 23.9999, lng: 90.4203 },
  },
  {
    region: "Dhaka",
    district: "Gopalganj",
    city: "Gopalganj",
    covered_area: ["Tungipara", "Kotalipara", "Kashiani", "Muksudpur"],
    coords: { lat: 23.0052, lng: 89.8266 },
  },
  {
    region: "Dhaka",
    district: "Kishoreganj",
    city: "Kishoreganj",
    covered_area: [
      "Bajitpur",
      "Kuliarchar",
      "Pakundia",
      "Austagram",
      "Hossainpur",
      "Karimganj",
      "Katiadi",
      "Mithamain",
      "Nikli",
      "Tarail",
      "Itna",
      "Bhairab",
    ],
    coords: { lat: 24.426, lng: 90.7829 },
  },
  {
    region: "Dhaka",
    district: "Madaripur",
    city: "Madaripur",
    covered_area: ["Rajoir", "Kalkini", "Shibchar", "Dasar"],
    coords: { lat: 23.17, lng: 90.2 },
  },
  {
    region: "Dhaka",
    district: "Manikganj",
    city: "Manikganj",
    covered_area: [
      "Saturia",
      "Shivalaya",
      "Ghior",
      "Singair",
      "Harirampur",
      "Doulatpur",
      "Shibalaya",
    ],
    coords: { lat: 23.8617, lng: 89.9767 },
  },
  {
    region: "Dhaka",
    district: "Munshiganj",
    city: "Munshiganj",
    covered_area: [
      "Sreenagar",
      "Lohajang",
      "Sirajdikhan",
      "Tongibari",
      "Gazaria",
      "Muktarpur",
    ],
    coords: { lat: 23.55, lng: 90.5305 },
  },
  {
    region: "Dhaka",
    district: "Narayanganj",
    city: "Narayanganj",
    covered_area: [
      "Fatullah",
      "Siddhirganj",
      "Rupganj",
      "Araihazar",
      "Bandar",
      "Sonargaon",
    ],
    coords: { lat: 23.62, lng: 90.5 },
  },
  {
    region: "Dhaka",
    district: "Narsingdi",
    city: "Narsingdi",
    covered_area: ["Palash", "Belabo", "Raipura", "Shibpur", "Monohardi"],
    coords: { lat: 23.9226, lng: 90.7156 },
  },
  {
    region: "Dhaka",
    district: "Rajbari",
    city: "Rajbari",
    covered_area: ["Pangsha", "Kalukhali", "Baliakandi", "Goalanda"],
    coords: { lat: 23.7576, lng: 89.65 },
  },
  {
    region: "Dhaka",
    district: "Shariatpur",
    city: "Shariatpur",
    covered_area: [
      "Zajira",
      "Naria",
      "Gosairhat",
      "Damudya",
      "Bhedarganj",
      "Jajira",
    ],
    coords: { lat: 23.22, lng: 90.4308 },
  },
  {
    region: "Dhaka",
    district: "Tangail",
    city: "Tangail",
    covered_area: [
      "Delduar",
      "Ghatail",
      "Kalihati",
      "Sakhipur",
      "Mirzapur",
      "Basail",
      "Bhuapur",
      "Dhanbari",
      "Gopalpur",
      "Madhupur",
      "Nagarpur",
    ],
    coords: { lat: 24.25, lng: 89.92 },
  },

  /* ─── CHATTOGRAM ─── */
  {
    region: "Chattogram",
    district: "Chattogram",
    city: "Chattogram",
    covered_area: [
      "Pahartali",
      "Kotwali",
      "Halishahar",
      "Panchlaish",
      "Agrabad",
      "Chandgaon",
      "Bayezid Bostami",
      "Chawkbazar",
      "Double Mooring",
      "Eidgaon",
      "Karnaphuli",
      "Patiya",
      "Rangunia",
      "Satkania",
      "Anwara",
      "Boalkhali",
    ],
    coords: { lat: 22.3569, lng: 91.7832 },
  },
  {
    region: "Chattogram",
    district: "Cox's Bazar",
    city: "Cox's Bazar",
    covered_area: [
      "Teknaf",
      "Ukhia",
      "Chakaria",
      "Ramu",
      "Maheshkhali",
      "Kutubdia",
      "Pekua",
      "Chokoria",
    ],
    coords: { lat: 21.4272, lng: 92.0165 },
  },
  {
    region: "Chattogram",
    district: "Cumilla",
    city: "Cumilla",
    covered_area: [
      "Laksam",
      "Debidwar",
      "Chandina",
      "Muradnagar",
      "Brahmanpara",
      "Barura",
      "Burichang",
      "Chauddagram",
      "Daudkandi",
      "Homna",
      "Meghna",
      "Monohorgonj",
      "Nangalkot",
      "Titas",
    ],
    coords: { lat: 23.4573, lng: 91.1809 },
  },
  {
    region: "Chattogram",
    district: "Brahmanbaria",
    city: "Brahmanbaria",
    covered_area: [
      "Nabinagar",
      "Ashuganj",
      "Sarail",
      "Bancharampur",
      "Bijoynagar",
      "Kasba",
      "Nasirnagar",
    ],
    coords: { lat: 23.9571, lng: 91.1116 },
  },
  {
    region: "Chattogram",
    district: "Chandpur",
    city: "Chandpur",
    covered_area: [
      "Haimchar",
      "Matlab North",
      "Matlab South",
      "Shahrasti",
      "Faridganj",
      "Hajiganj",
      "Kachua",
    ],
    coords: { lat: 23.2333, lng: 90.85 },
  },
  {
    region: "Chattogram",
    district: "Feni",
    city: "Feni",
    covered_area: [
      "Parshuram",
      "Daganbhuiyan",
      "Chhagalnaiya",
      "Sonagazi",
      "Fulgazi",
    ],
    coords: { lat: 23.0167, lng: 91.4 },
  },
  {
    region: "Chattogram",
    district: "Khagrachari",
    city: "Khagrachari",
    covered_area: [
      "Ramgarh",
      "Mahalchari",
      "Dighinala",
      "Lakshmichari",
      "Manikchhari",
      "Matiranga",
      "Panchari",
    ],
    coords: { lat: 23.1, lng: 91.9667 },
  },
  {
    region: "Chattogram",
    district: "Lakshmipur",
    city: "Lakshmipur",
    covered_area: ["Raipur", "Ramganj", "Kamalnagar", "Ramgati"],
    coords: { lat: 22.9444, lng: 90.8415 },
  },
  {
    region: "Chattogram",
    district: "Noakhali",
    city: "Noakhali",
    covered_area: [
      "Begumganj",
      "Senbagh",
      "Chatkhil",
      "Companiganj",
      "Hatiya",
      "Kabirhat",
      "Subarnachar",
    ],
    coords: { lat: 22.8245, lng: 91.0995 },
  },
  {
    region: "Chattogram",
    district: "Rangamati",
    city: "Rangamati",
    covered_area: [
      "Baghaichhari",
      "Kaptai",
      "Juraichhari",
      "Barkal",
      "Belaichhari",
      "Kawkhali",
      "Langadu",
      "Naniarchar",
      "Rajasthali",
    ],
    coords: { lat: 22.65, lng: 92.2 },
  },
  {
    region: "Chattogram",
    district: "Bandarban",
    city: "Bandarban",
    covered_area: [
      "Bandarban Sadar",
      "Thanchi",
      "Lama",
      "Rowangchhari",
      "Alikadam",
      "Naikhongchhari",
      "Ruma",
    ],
    coords: { lat: 22.1958, lng: 92.2186 },
  },

  /* ─── SYLHET ─── */
  {
    region: "Sylhet",
    district: "Sylhet",
    city: "Sylhet",
    covered_area: [
      "Zindabazar",
      "Ambarkhana",
      "Dargah Gate",
      "South Surma",
      "Subid Bazar",
      "Tilagor",
      "Balaganj",
      "Beanibazar",
      "Bishwanath",
      "Companiganj",
      "Fenchuganj",
      "Golapganj",
      "Gowainghat",
      "Jaintiapur",
      "Kanaighat",
      "Osmani Nagar",
    ],
    coords: { lat: 24.8949, lng: 91.8662 },
  },
  {
    region: "Sylhet",
    district: "Moulvibazar",
    city: "Moulvibazar",
    covered_area: [
      "Sreemangal",
      "Kamalganj",
      "Kulaura",
      "Barlekha",
      "Juri",
      "Rajnagar",
    ],
    coords: { lat: 24.4826, lng: 91.7832 },
  },
  {
    region: "Sylhet",
    district: "Habiganj",
    city: "Habiganj",
    covered_area: [
      "Shaistaganj",
      "Madhabpur",
      "Chunarughat",
      "Nabiganj",
      "Ajmiriganj",
      "Bahubal",
      "Baniachong",
      "Lakhai",
    ],
    coords: { lat: 24.3745, lng: 91.4026 },
  },
  {
    region: "Sylhet",
    district: "Sunamganj",
    city: "Sunamganj",
    covered_area: [
      "Jagannathpur",
      "Chhatak",
      "Tahirpur",
      "Dowarabazar",
      "Bishwamvarpur",
      "Derai",
      "Dharampasha",
      "Jamalganj",
      "Sulla",
      "Shalla",
    ],
    coords: { lat: 25.0658, lng: 91.395 },
  },

  /* ─── RANGPUR ─── */
  {
    region: "Rangpur",
    district: "Rangpur",
    city: "Rangpur",
    covered_area: [
      "Jahaj Company",
      "Pairaband",
      "Mahiganj",
      "Satmatha",
      "Lalbagh",
      "Badarganj",
      "Gangachara",
      "Kaunia",
      "Mithapukur",
      "Pirgachha",
      "Pirganj",
      "Taraganj",
    ],
    coords: { lat: 25.746, lng: 89.2752 },
  },
  {
    region: "Rangpur",
    district: "Dinajpur",
    city: "Dinajpur",
    covered_area: [
      "Birampur",
      "Fulbari",
      "Parbatipur",
      "Nawabganj",
      "Birganj",
      "Biral",
      "Bochaganj",
      "Chirirbandar",
      "Ghoraghat",
      "Hakimpur",
      "Kaharole",
      "Khansama",
    ],
    coords: { lat: 25.6275, lng: 88.6414 },
  },
  {
    region: "Rangpur",
    district: "Thakurgaon",
    city: "Thakurgaon",
    covered_area: ["Pirganj", "Ranisankail", "Baliadangi", "Haripur"],
    coords: { lat: 26.0333, lng: 88.466 },
  },
  {
    region: "Rangpur",
    district: "Panchagarh",
    city: "Panchagarh",
    covered_area: ["Tetulia", "Boda", "Atwari", "Debiganj"],
    coords: { lat: 26.3411, lng: 88.5658 },
  },
  {
    region: "Rangpur",
    district: "Nilphamari",
    city: "Nilphamari",
    covered_area: ["Saidpur", "Domar", "Jaldhaka", "Dimla", "Kishoreganj"],
    coords: { lat: 25.931, lng: 88.856 },
  },
  {
    region: "Rangpur",
    district: "Lalmonirhat",
    city: "Lalmonirhat",
    covered_area: ["Hatibandha", "Patgram", "Aditmari", "Kaliganj"],
    coords: { lat: 25.9167, lng: 89.1662 },
  },
  {
    region: "Rangpur",
    district: "Kurigram",
    city: "Kurigram",
    covered_area: [
      "Nageshwari",
      "Bhurungamari",
      "Chilmari",
      "Ulipur",
      "Char Rajibpur",
      "Phulbari",
      "Rajarhat",
      "Roumari",
    ],
    coords: { lat: 25.8054, lng: 89.65 },
  },
  {
    region: "Rangpur",
    district: "Gaibandha",
    city: "Gaibandha",
    covered_area: [
      "Gobindaganj",
      "Sundarganj",
      "Palashbari",
      "Phulchhari",
      "Saghata",
      "Sadullapur",
    ],
    coords: { lat: 25.3288, lng: 89.5418 },
  },

  /* ─── KHULNA ─── */
  {
    region: "Khulna",
    district: "Khulna",
    city: "Khulna",
    covered_area: [
      "Sonadanga",
      "Khalishpur",
      "Daulatpur",
      "Shib Bari",
      "Boyra",
      "Batiaghata",
      "Dacope",
      "Dumuria",
      "Dighalia",
      "Koyra",
      "Paikgachha",
      "Phultala",
      "Rupsa",
      "Terokhada",
    ],
    coords: { lat: 22.8456, lng: 89.5672 },
  },
  {
    region: "Khulna",
    district: "Jessore",
    city: "Jessore",
    covered_area: [
      "Chowgachha",
      "Bagharpara",
      "Manirampur",
      "Abhaynagar",
      "Keshabpur",
      "Sharsha",
      "Jhikargachha",
    ],
    coords: { lat: 23.17, lng: 89.2167 },
  },
  {
    region: "Khulna",
    district: "Satkhira",
    city: "Satkhira",
    covered_area: [
      "Tala",
      "Assasuni",
      "Kalaroa",
      "Debhata",
      "Kaliganj",
      "Shyamnagar",
    ],
    coords: { lat: 22.7085, lng: 89.0809 },
  },
  {
    region: "Khulna",
    district: "Bagerhat",
    city: "Bagerhat",
    covered_area: [
      "Mongla",
      "Rampal",
      "Fakirhat",
      "Kachua",
      "Chitalmari",
      "Morelganj",
      "Mollahat",
      "Sharankhola",
    ],
    coords: { lat: 22.6516, lng: 89.7926 },
  },
  {
    region: "Khulna",
    district: "Magura",
    city: "Magura",
    covered_area: ["Sreepur", "Mohammadpur", "Shalikha"],
    coords: { lat: 23.4853, lng: 89.4194 },
  },
  {
    region: "Khulna",
    district: "Narail",
    city: "Narail",
    covered_area: ["Lohagara", "Kalia", "Narail Sadar"],
    coords: { lat: 23.1667, lng: 89.5 },
  },
  {
    region: "Khulna",
    district: "Jhenaidah",
    city: "Jhenaidah",
    covered_area: [
      "Harinakunda",
      "Shailkupa",
      "Kaliganj",
      "Kotchandpur",
      "Maheshpur",
    ],
    coords: { lat: 23.5333, lng: 89.1833 },
  },
  {
    region: "Khulna",
    district: "Chuadanga",
    city: "Chuadanga",
    covered_area: ["Alamdanga", "Damurhuda", "Jibannagar"],
    coords: { lat: 23.64, lng: 88.85 },
  },
  {
    region: "Khulna",
    district: "Meherpur",
    city: "Meherpur",
    covered_area: ["Mujibnagar", "Gangni"],
    coords: { lat: 23.7623, lng: 88.6318 },
  },
  {
    region: "Khulna",
    district: "Kushtia",
    city: "Kushtia",
    covered_area: [
      "Kumarkhali",
      "Khoksa",
      "Mirpur",
      "Bheramara",
      "Daulatpur",
      "Kushtia Sadar",
    ],
    coords: { lat: 23.9013, lng: 89.122 },
  },

  /* ─── RAJSHAHI ─── */
  {
    region: "Rajshahi",
    district: "Rajshahi",
    city: "Rajshahi",
    covered_area: [
      "Boalia",
      "Rajpara",
      "Motihar",
      "Shah Makhdum",
      "Paba",
      "Bagha",
      "Bagmara",
      "Charghat",
      "Durgapur",
      "Godagari",
      "Mohanpur",
      "Puthia",
      "Tanore",
    ],
    coords: { lat: 24.3745, lng: 88.6087 },
  },
  {
    region: "Rajshahi",
    district: "Natore",
    city: "Natore",
    covered_area: ["Baraigram", "Bagatipara", "Lalpur", "Singra", "Gurudaspur"],
    coords: { lat: 24.4167, lng: 89.0 },
  },
  {
    region: "Rajshahi",
    district: "Naogaon",
    city: "Naogaon",
    covered_area: [
      "Manda",
      "Sapahar",
      "Porsha",
      "Patnitala",
      "Badalgachhi",
      "Dhamoirhat",
      "Mahadebpur",
      "Niamatpur",
      "Raninagar",
    ],
    coords: { lat: 24.8236, lng: 88.93 },
  },
  {
    region: "Rajshahi",
    district: "Chapainawabganj",
    city: "Chapainawabganj",
    covered_area: ["Shibganj", "Bholahat", "Gomostapur", "Nachole", "Rohanpur"],
    coords: { lat: 24.5962, lng: 88.27 },
  },
  {
    region: "Rajshahi",
    district: "Pabna",
    city: "Pabna",
    covered_area: [
      "Ishwardi",
      "Bera",
      "Chatmohar",
      "Atgharia",
      "Bhangura",
      "Faridpur",
      "Santhia",
      "Sujanagar",
    ],
    coords: { lat: 24.0037, lng: 89.2331 },
  },
  {
    region: "Rajshahi",
    district: "Sirajganj",
    city: "Sirajganj",
    covered_area: [
      "Ullapara",
      "Kazipur",
      "Shahjadpur",
      "Belkuchi",
      "Chauhali",
      "Kamarkhanda",
      "Raiganj",
      "Tarash",
    ],
    coords: { lat: 24.45, lng: 89.7167 },
  },
  {
    region: "Rajshahi",
    district: "Joypurhat",
    city: "Joypurhat",
    covered_area: ["Akkelpur", "Kalai", "Panchbibi", "Khetlal"],
    coords: { lat: 25.0953, lng: 89.0412 },
  },
  {
    region: "Rajshahi",
    district: "Bogura",
    city: "Bogura",
    covered_area: [
      "Sariakandi",
      "Sonatola",
      "Gabtali",
      "Sherpur",
      "Shajahanpur",
      "Adamdighi",
      "Dhunat",
      "Dupchanchia",
      "Kahaloo",
      "Nandigram",
      "Shibganj",
    ],
    coords: { lat: 24.85, lng: 89.37 },
  },

  /* ─── BARISAL ─── */
  {
    region: "Barisal",
    district: "Barisal",
    city: "Barisal",
    covered_area: [
      "Band Road",
      "Cox's Road",
      "Kawnia",
      "Rupatali",
      "Nathullabad",
      "Agailjhara",
      "Babuganj",
      "Bakerganj",
      "Banaripara",
      "Gaurnadi",
      "Hizla",
      "Mehendiganj",
      "Muladi",
      "Uzirpur",
      "Wazirpur",
    ],
    coords: { lat: 22.701, lng: 90.3535 },
  },
  {
    region: "Barisal",
    district: "Bhola",
    city: "Bhola",
    covered_area: [
      "Borhanuddin",
      "Tazumuddin",
      "Daulatkhan",
      "Char Fasson",
      "Lalmohan",
      "Manpura",
      "Char Khalifa",
    ],
    coords: { lat: 22.685, lng: 90.6311 },
  },
  {
    region: "Barisal",
    district: "Patuakhali",
    city: "Patuakhali",
    covered_area: [
      "Kalapara",
      "Mirzaganj",
      "Dashmina",
      "Galachipa",
      "Bauphal",
      "Dumki",
      "Ratnapur",
    ],
    coords: { lat: 22.35, lng: 90.3333 },
  },
  {
    region: "Barisal",
    district: "Pirojpur",
    city: "Pirojpur",
    covered_area: [
      "Mathbaria",
      "Bhandaria",
      "Kawkhali",
      "Nazirpur",
      "Indurkani",
      "Nesarabad",
      "Zianagar",
    ],
    coords: { lat: 22.5833, lng: 89.975 },
  },
  {
    region: "Barisal",
    district: "Barguna",
    city: "Barguna",
    covered_area: ["Amtali", "Patharghata", "Betagi", "Bamna", "Taltali"],
    coords: { lat: 22.1667, lng: 90.1167 },
  },
  {
    region: "Barisal",
    district: "Jhalokati",
    city: "Jhalokati",
    covered_area: ["Nalchity", "Rajapur", "Kathalia"],
    coords: { lat: 22.6417, lng: 90.2167 },
  },

  /* ─── MYMENSINGH ─── */
  {
    region: "Mymensingh",
    district: "Mymensingh",
    city: "Mymensingh",
    covered_area: [
      "Trishal",
      "Muktagachha",
      "Bhaluka",
      "Phulpur",
      "Haluaghat",
      "Dhobaura",
      "Fulbaria",
      "Gaffargaon",
      "Gauripur",
      "Ishwarganj",
      "Nandail",
      "Tarakanda",
    ],
    coords: { lat: 24.7539, lng: 90.3987 },
  },
  {
    region: "Mymensingh",
    district: "Netrokona",
    city: "Netrokona",
    covered_area: [
      "Khaliajuri",
      "Mohanganj",
      "Durgapur",
      "Barhatta",
      "Atpara",
      "Kalmakanda",
      "Kendua",
      "Madan",
      "Purbadhala",
    ],
    coords: { lat: 24.8833, lng: 90.7333 },
  },
  {
    region: "Mymensingh",
    district: "Jamalpur",
    city: "Jamalpur",
    covered_area: [
      "Madarganj",
      "Islampur",
      "Sarishabari",
      "Baksiganj",
      "Dewanganj",
      "Melandaha",
    ],
    coords: { lat: 24.9167, lng: 89.9333 },
  },
  {
    region: "Mymensingh",
    district: "Sherpur",
    city: "Sherpur",
    covered_area: ["Nakla", "Nalitabari", "Jhenaigati", "Sreebardi"],
    coords: { lat: 25.0333, lng: 90.0333 },
  },
];

export default coverageData;

/* ─────────────────────────────────────────────
   UTILITY: find coverage entry by typed address
   Returns { district, region, coords } or null
───────────────────────────────────────────── */
export function matchCoverage(addressText) {
  if (!addressText) return null;
  const lower = addressText.toLowerCase();

  // Try to match covered_area first (most specific)
  for (const entry of coverageData) {
    for (const area of entry.covered_area) {
      if (lower.includes(area.toLowerCase())) return entry;
    }
  }
  // Fall back to district / city match
  for (const entry of coverageData) {
    if (
      lower.includes(entry.district.toLowerCase()) ||
      lower.includes(entry.city.toLowerCase())
    )
      return entry;
  }
  return null;
}

/* Extract unique regions */
export const REGIONS = [...new Set(coverageData.map((e) => e.region))].sort();

/* All districts flat */
export const ALL_DISTRICTS = coverageData.map((e) => e.district).sort();
